#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("ATMoviePlayer.Resource", IsApplication=true)]

namespace ATMoviePlayer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int button_typesel_height = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int list_thumbnail_height = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int list_thumbnail_width = 2130968577;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int listView1 = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int mediaTitle = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int multi_sel = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int play_all = 2131165190;
			
			// aapt resource value: 0x7f070009
			public const int random_all = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int repeat_all = 2131165192;
			
			// aapt resource value: 0x7f070002
			public const int selectedCheckBox = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int thumbImage = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int videoPreview = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MediaItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MoviePlayer = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int MainMenu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button_label_movie = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int button_label_music = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int menu_multisel = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int menu_multisel_checked = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int menu_play = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int menu_random = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int menu_random_checked = 2131034122;
			
			// aapt resource value: 0x7f050007
			public const int menu_repeat = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int menu_repeat_checked = 2131034120;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
